language: node_js

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
    - export CXX="g++-4.8"

cache:
  directories:
    - node_modules

node_js:
    - '4.2'
    - '5.0'

services:
    - redis-server

before_script:
    - npm install juttle@0.1.x
    - npm install -g jshint
    - npm install -g jscs

script:
    - npm run -s lint
    - npm test
